---
# This playbook deploys a simple standalone Tomcat 7 server.

- name: Ansible playbook to configure docker containers with Tomcat7
  hosts: localhost
  remote_user: root

  vars:
    - tomcat_port: 8088
    - admin_username: admin
    - admin_password: test@123
    
  roles:
    - docker-tomcat7