---
- name: Configure Tomcat server
  template: src=server.xml dest=/etc/tomcat7/

- name: Configure Tomcat Authentication
  file: src=tomcat-users.xml dest=/etc/tomcat7/

- name: Sets Tomcat Resource Utilization
  file: src=tomcat7 dest=/etc/default/tomcat7

- name: Start Tomcat
  service: name=tomcat7 state=started enabled=yes

- name: wait for tomcat to start
  wait_for: port={{tomcat_port}}